# Generated by Django 2.2 on 2019-04-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_assigment_ingredient_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
    ]
