# Generated by Django 2.2.1 on 2019-05-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rawmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='production',
            field=models.TextField(default='fabrica'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='material_type',
            field=models.IntegerField(default=1),
        ),
    ]
