# Generated by Django 2.2.1 on 2019-05-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190524_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdOc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField()),
                ('develop', models.TextField()),
                ('production', models.TextField()),
            ],
        ),
    ]
